### ISSUE TITLE
about the paper

### ISSUE THREAD

**Issue by hkkevinhf** [jinyeying/DC-ShadowNet-Hard-and-Soft-Shadow-Removal#1]
Hi, i am interested in this work. I am wondering if you could release the original paper ? Thanks.

**Comment by jinyeying** [comment]
The paper officially being released by ICCV in October. Attached is the link:
https://openaccess.thecvf.com/content/ICCV2021/papers/Jin_DC-ShadowNet_Single-Image_Hard_and_Soft_Shadow_Removal_Using_Unsupervised_Domain-Classifier_ICCV_2021_paper.pdf
