### ISSUE TITLE
 the pre-training code

### ISSUE THREAD

**Issue by wusiqi521** [jinyeying/DC-ShadowNet-Hard-and-Soft-Shadow-Removal#11]
Sorry to bother you, can you provide the pre-training code, I want to train the model you built locally.My email is 2102520021006@stu.bucea.edu.cn

**Comment by jinyeying** [comment]
> Sorry to bother you, can you provide the pre-training code, I want to train the model you built locally.My email is [2102520021006@stu.bucea.edu.cn](mailto:2102520021006@stu.bucea.edu.cn)

Hi,
Thank you for your interest in our works.
Shadow-Free Chromaticity Maps are the implementation of Finlayson's paper,
On the removal of shadows from images (TPAMI,05).

If you want the code, you can contact my email sent by your affiliation email with your signed name.
