### ISSUE TITLE
datasets preprocessing code

### ISSUE THREAD

**Issue by WangJunjie97** [jinyeying/DC-ShadowNet-Hard-and-Soft-Shadow-Removal#12]
Hi! Your work is great. Can you send me a copy of the data processing code? My email address is: wbwangjunjie@stu.cqut.edu.cn, thank you very much.

**Comment by jinyeying** [comment]
> Hi! Your work is great. Can you send me a copy of the data processing code? My email address is: [wbwangjunjie@stu.cqut.edu.cn](mailto:wbwangjunjie@stu.cqut.edu.cn), thank you very much.

Hi,
Thank you for your interest in our works.
Shadow-Free Chromaticity Maps are the implementation of Finlayson's paper,
On the removal of shadows from images (TPAMI,05).

If you want the code, you can contact my email sent by your affiliation email with your signed name.
