### ISSUE TITLE
建立環境失敗

### ISSUE THREAD

**Issue by ghost** [jinyeying/DC-ShadowNet-Hard-and-Soft-Shadow-Removal#13]
conda env create -f shadow_env.yml

一直失敗，不曉得是否有更新?
win10 python 3.10

**Comment by jinyeying** [comment]
> conda env create -f shadow_env.yml
> 
> 一直失敗，不曉得是否有更新? win10 python 3.10

不要用win，conda create -n shadow python=3.7 pytorch=1.1.0 torchvision=0.3.0

**Comment by ghost** [comment]
我沒有其他作業系統 只能用win10
我照著conda create -n shadow python=3.7 pytorch=1.1.0 torchvision=0.3.0建立環境後
下載的ISTD dataset跟ISTD預權重(results/ISTD/model/)

輸入
python main_test.py --dataset ISTD --datasetpath dataset --use_original_name False
顯示錯誤

number of epochs must be larger than or equal to one

##### Information #####
# dataset :  ISTD
# datasetpath :  dataset
Traceback (most recent call last):
  File "main_test.py", line 88, in <module>
    main()
  File "main_test.py", line 81, in main
    gan.build_model()
  File "C:\Users\User\Desktop\DC\DCShadowNet_test.py", line 85, in build_model
    self.testA = ImageFolder(os.path.join('dataset', self.datasetpath, 'testA'), self.test_transform)
  File "C:\Users\User\Desktop\DC\dataset.py", line 107, in __init__
    target_transform=target_transform)
  File "C:\Users\User\Desktop\DC\dataset.py", line 47, in __init__
    "Supported extensions are: " + ",".join(extensions)))
RuntimeError: Found 0 files in subfolders of: dataset\dataset\testA
Supported extensions are: .jpg,.jpeg,.png,.ppm,.bmp,.pgm,.tif

不知道哪邊出錯誤，再麻煩你呢，謝謝作者

**Comment by jinyeying** [comment]
> 我沒有其他作業系統 只能用win10 我照著conda create -n shadow python=3.7 pytorch=1.1.0 torchvision=0.3.0建立環境後 下載的ISTD dataset跟ISTD預權重(results/ISTD/model/)
> 
> 輸入 python main_test.py --dataset ISTD --datasetpath dataset --use_original_name False 顯示錯誤
> 
> number of epochs must be larger than or equal to one
> 
> ##### Information
> # dataset : ISTD
> # datasetpath : dataset
> Traceback (most recent call last): File "main_test.py", line 88, in main() File "main_test.py", line 81, in main gan.build_model() File "C:\Users\User\Desktop\DC\DCShadowNet_test.py", line 85, in build_model self.testA = ImageFolder(os.path.join('dataset', self.datasetpath, 'testA'), self.test_transform) File "C:\Users\User\Desktop\DC\dataset.py", line 107, in **init** target_transform=target_transform) File "C:\Users\User\Desktop\DC\dataset.py", line 47, in **init** "Supported extensions are: " + ",".join(extensions))) RuntimeError: Found 0 files in subfolders of: dataset\dataset\testA Supported extensions are: .jpg,.jpeg,.png,.ppm,.bmp,.pgm,.tif
> 
> 不知道哪邊出錯誤，再麻煩你呢，謝謝作者

把路径弄对

**Comment by jinyeying** [comment]
> 我沒有其他作業系統 只能用win10 我照著conda create -n shadow python=3.7 pytorch=1.1.0 torchvision=0.3.0建立環境後 下載的ISTD dataset跟ISTD預權重(results/ISTD/model/)
> 
> 輸入 python main_test.py --dataset ISTD --datasetpath dataset --use_original_name False 顯示錯誤
> 
> number of epochs must be larger than or equal to one
> 
> ##### Information
> # dataset : ISTD
> # datasetpath : dataset
> Traceback (most recent call last): File "main_test.py", line 88, in main() File "main_test.py", line 81, in main gan.build_model() File "C:\Users\User\Desktop\DC\DCShadowNet_test.py", line 85, in build_model self.testA = ImageFolder(os.path.join('dataset', self.datasetpath, 'testA'), self.test_transform) File "C:\Users\User\Desktop\DC\dataset.py", line 107, in **init** target_transform=target_transform) File "C:\Users\User\Desktop\DC\dataset.py", line 47, in **init** "Supported extensions are: " + ",".join(extensions))) RuntimeError: Found 0 files in subfolders of: dataset\dataset\testA Supported extensions are: .jpg,.jpeg,.png,.ppm,.bmp,.pgm,.tif
> 
> 不知道哪邊出錯誤，再麻煩你呢，謝謝作者

环境问题可以参考这个视频:
【AI 夜间图像增强（再黑也能看见）-哔哩哔哩】 https://b23.tv/nfim0EF
