### ISSUE TITLE
How to select the unpaired training data on ISTD and SRD, which contain paired shadow/shadow-free images?

### ISSUE THREAD

**Issue by lxxcontinue** [jinyeying/DC-ShadowNet-Hard-and-Soft-Shadow-Removal#15]
In order to construct unpaired data, for unpaired training on the ISTD train dataset, the shadow and shadow free images were randomly sampled? But such random sampling may yield paired data. ISTD have different shadow images for the same shadow-free image.
Was I wrong about the way to sample the unpaired data

**Comment by jinyeying** [comment]
> In order to construct unpaired data, for unpaired training on the ISTD train dataset, the shadow and shadow free images were randomly sampled? But such random sampling may yield paired data. ISTD have different shadow images for the same shadow-free image. Was I wrong about the way to sample the unpaired data

We followed the data loader of MaskShadowGAN
        if self.unaligned:
            item_B = self.transform(Image.open(self.files_B[random.randint(0, len(self.files_B) - 1)]))

**Comment by lxxcontinue** [comment]
This random sampling method may sample ground truth, so it may not be true unpaired data. Maybe this situation can be ignored?

**Comment by jinyeying** [comment]
> ground truth

May have a chance to sample the ground truth for training, but there are 1330 training images for AISTD/ISTD, I think the chance is small.

If you want totally unpaired, you can try the USR dataset proposed by MaskShadowGAN.

**Comment by lxxcontinue** [comment]
OK ! Thank you for your response : )
