### ISSUE TITLE
Can't reproduce the visualization results in the paper

### ISSUE THREAD

**Issue by fawnliu** [jinyeying/DC-ShadowNet-Hard-and-Soft-Shadow-Removal#16]
Can you tell me how to visualize the attention map in Figure 7? I visualized the attention map in column 3 with the released model, but I can not obtain the same visualization results in your paper.

<img width="637" alt="WeChat58ecc0dc23b3d916dbf5d7c5d31134e6" src="https://user-images.githubusercontent.com/17973682/204956440-e691bbad-6630-4729-b74e-43086aa18b77.png">

**Comment by jinyeying** [comment]
> Can you tell me how to visualize the attention map in Figure 7? I visualized the attention map in column 3 with the released model, but I can not obtain the same visualization results in your paper.
> 
> <img alt="WeChat58ecc0dc23b3d916dbf5d7c5d31134e6" width="637" src="https://user-images.githubusercontent.com/17973682/204956440-e691bbad-6630-4729-b74e-43086aa18b77.png">

Hi, thanks for your interest.

Our attention visualization results are during training.

**Comment by fawnliu** [comment]
Thanks for your prompt reply. I don't understand why there is such a big difference between the results obtained during the training and testing phases. Can you tell me more about this attention map visualization?

Besides, I have tested several images you provided and found that they are difficult to focus on the corresponding shadow areas as the attention map in the paper.

![image](https://user-images.githubusercontent.com/17973682/205235855-3e8bc1f5-35ee-4e82-b8c7-8518065ea792.png)

**Comment by jinyeying** [comment]
> 

![image](https://user-images.githubusercontent.com/36725804/205279152-6b5006e0-d256-4443-bc86-92c9d67c04e3.png)
