### ISSUE TITLE
Can you send me the SRD test dataset?

### ISSUE THREAD

**Issue by XiaMoooo** [jinyeying/DC-ShadowNet-Hard-and-Soft-Shadow-Removal#17]
I found out that the SRD official link is not working. I tried to contact the author but failed. So, please, do you still have the relevant dataset? If you still have it, can you send me an email? My email : fj031717xiamo@163.com

**Comment by jinyeying** [comment]
https://pan.baidu.com/s/1mj3BoRQ#list/path=%2F

**Comment by XiaMoooo** [comment]
Thank you very much for your reply！I also found this training dataset, but unfortunately the test dataset is not working, do you have the **SRD test** dataset please?

**Comment by jinyeying** [comment]
https://www.dropbox.com/s/pooxomexic3flfa/test_data.rar?dl=0

**Comment by XiaMoooo** [comment]
I received it, thank you very very much!
