### ISSUE TITLE
datasets preprocessing code

### ISSUE THREAD

**Issue by jennyhappy722** [jinyeying/DC-ShadowNet-Hard-and-Soft-Shadow-Removal#19]
hi, thank you for your great work! I don't know how to get the Shadow-Free Chromaticity Maps, could you give me a hand?
jenny72227@gmail.com

**Comment by jennyhappy722** [comment]
@jinyeying  I tried to send an email to you. Sorry, could you please share it with me? I really need it. Thank you.

**Comment by Alive59** [comment]
The chromaticity maps would not be read when setting use_ch_loss to False.

**Comment by jinyeying** [comment]
> @jinyeying I tried to send an email to you. Sorry, could you please share it with me? I really need it. Thank you.

I will release it after the AAAI deadline.

**Comment by shubhoppo** [comment]
Any update on chromaticity map?

**Comment by jinyeying** [comment]
> Any update on chromaticity map?

Hi, I have updated in 0_Shadow-Free_Chromaticity_matlab\physics_single.m. Thanks for waiting!
