### ISSUE TITLE
data processing

### ISSUE THREAD

**Issue by CV-deeplearning** [jinyeying/DC-ShadowNet-Hard-and-Soft-Shadow-Removal#2]
hi, thank you for your great work! I don't know how to get the Shadow-Free Chromaticity Maps, could you give me a hand?
my e-mail is 1151583746@qq.com

**Comment by jinyeying** [comment]
> hi, thank you for your great work! I don't know how to get the Shadow-Free Chromaticity Maps, could you give me a hand? my e-mail is [1151583746@qq.com](mailto:1151583746@qq.com)

Hi, thank you for your interest in our works. Shadow-Free Chromaticity Maps are implementation of Finlayson paper,
On the removal of shadows from images (TPAMI,05). We will upload a sample code example.

**Comment by jinyeying** [comment]
> 1151583746@qq.com
I have sent you the code.

**Comment by jennyhappy722** [comment]
@jinyeying  Hello, Can you send it ?
jenny72227@gmail.com

**Comment by Jaddde** [comment]
@jinyeying Hello @jinyeying ,thank you for your excellent work! I am interested in obtaining the Shadow-Free Chromaticity Maps as well. If it's not too much trouble, could you please share the code with me? I would greatly appreciate it. Thank you! my email is 1375360327@qq.com

**Comment by Jaddde** [comment]
@CV-deeplearning Hello！ I am interested in obtaining the Shadow-Free Chromaticity Maps as well. If it's not too much trouble, could you please share the code with me? I would greatly appreciate it. Thank you! my email is [1375360327@qq.com](mailto:1375360327@qq.com)
