### ISSUE TITLE
RMSE 

### ISSUE THREAD

**Issue by jennyhappy722** [jinyeying/DC-ShadowNet-Hard-and-Soft-Shadow-Removal#20]
May I ask how the RMSE  calculated in shaded and non_shadow parts? 
Is there a formula?

**Comment by jinyeying** [comment]
> May I ask how the RMSE calculated in shaded and non_shadow parts? Is there a formula?

can see our evaluation Matlab code

**Comment by jennyhappy722** [comment]
Thank you.

**Comment by jennyhappy722** [comment]
I tried to send an email to you. 
Sorry, could you please share datasets preprocessing code with me? I really need it. Thank you.
