### ISSUE TITLE
表格數據

### ISSUE THREAD

**Issue by Taro850441** [jinyeying/DC-ShadowNet-Hard-and-Soft-Shadow-Removal#22]
不好意思打擾您
我能詢問看看論文中只有Input Image中的RMSE中 ALL、S、NS如何計算呢?
這邊有看計算RMSE的程式碼，但是如果沒有預測中的結果，只有Input image該如何計算呢?
因為我有拿了自己的資料集去訓練
感謝

**Comment by jinyeying** [comment]
> 不好意思打擾您 我能詢問看看論文中只有Input Image中的RMSE中 ALL、S、NS如何計算呢? 這邊有看計算RMSE的程式碼，但是如果沒有預測中的結果，只有Input image該如何計算呢? 因為我有拿了自己的資料集去訓練 感謝

你就把Input image的路径放在recovered_recovery就可以了

**Comment by Taro850441** [comment]
好的謝謝
