### ISSUE TITLE
論文中Gs Gsf Dsf Ds

### ISSUE THREAD

**Issue by Taro850441** [jinyeying/DC-ShadowNet-Hard-and-Soft-Shadow-Removal#25]
不好意思在詢問一個問題，抱歉一直詢問您，論文中的架構圖只有Gs跟Dsf，在論文中會去計算Cycle Consistence loss，想詢問說Gs跟Gsf架構是一樣的嗎?因為好像沒有用到Gsf生成有陰影的圖片

**Comment by jinyeying** [comment]
> 

框架一样的，一个去阴影的，另外一个生成阴影的

**Comment by jinyeying** [comment]
> Gs是去阴影的，另外一个Gsf生成阴影的。因为我们不关注生成有陰影的部分。Cycle Consistence loss那些是为了unpaired，也是unsupervised的框架设计的。
