### ISSUE TITLE
用matlab处理无阴影色度图30多分钟生成一张图片正常吗

### ISSUE THREAD

**Issue by Amy-214** [jinyeying/DC-ShadowNet-Hard-and-Soft-Shadow-Removal#26]
用作者提供的0_Shadow-Free_Chromaticity_matlab 中的physics_all.m把SRD trainA中两千多张图片处理生成无阴影色度图，发现每处理一张都需要三十多分钟，用的RTX5000 16G，这正常吗？或者作者大大可以提供处理好的无阴影色度图吗？

**Comment by jinyeying** [comment]
Matlab的code对于高分辨率的图，处理确实比较慢，主要原因在算法有个算entropy min的时候要0-180度投影去算。不介意准确度的话，可以试试python code，会快一些。

**Comment by Amy-214** [comment]
您好，我在研究过程中又产生了一个疑问，域分类器是为了判断输入图像是否有阴影，那么输入是无阴影图像时，生成器会生成阴影图像还是无阴影图像呀
