### ISSUE TITLE
LRSS training dataset

### ISSUE THREAD

**Issue by Jaddde** [jinyeying/DC-ShadowNet-Hard-and-Soft-Shadow-Removal#27]
Hi jinyeying, really appreciate your work and thx for ur sharing!
However, i was wondering if u have a bigger training dataset of soft shadow, bc the training dataset of LRSS u shared contains only 32 images(it's a bit hard to gain a great results with such a small dataset for other purposes)

**Comment by jinyeying** [comment]
Hi, the results on lrss, is used the pretrained model on the SRD dataset, fine-tuned on lrss.

**Comment by Jaddde** [comment]
got it! thx for ur reply
