### ISSUE TITLE
conda env create -f shadow_env.yml can't work. (win11)

### ISSUE THREAD

**Issue by HIHHIYAYAYOO** [jinyeying/DC-ShadowNet-Hard-and-Soft-Shadow-Removal#28]
conda env create -f shadow_env.yml

done
Channels:
 - pytorch
 - conda-forge
 - defaults
Platform: win-64
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - zstd==1.4.5=h9ceee32_0
  - zlib==1.2.11=h7b6447c_3
  - zeromq==4.3.3=h58526e2_3
  - yaml==0.2.5=h516909a_0
  - websocket-client==0.57.0=py37h89c1867_3
  - tornado==6.1=py37h4abf009_0
  - torchvision==0.5.0=py37_cu100
  - sqlite==3.33.0=h62c20be_0
  - six==1.15.0=py37h06a4308_0
  - readline==8.0=h7b6447c_0
  - pyzmq==20.0.0=py37h5a562af_1
  - pyyaml==5.3.1=py37hb5d75c8_1
  - pywavelets==1.1.1=py37h161383b_3
  - pytorch==1.4.0=py3.7_cuda10.0.130_cudnn7.6.3_0
  - pysocks==1.7.1=py37he5f6b98_2
  - pillow==8.0.1=py37he98fc37_0
  - pathlib==1.0.1=py37h89c1867_4
  - ninja==1.10.2=py37hff7bd54_0
  - ncurses==6.2=he6710b0_1
  - mkl_random==1.1.1=py37h0573a6f_0
  - mkl_fft==1.2.0=py37h23d657b_0
  - mkl-service==2.3.0=py37he8ac12f_0
  - matplotlib-base==3.2.2=py37h1d35a4c_1
  - lz4-c==1.9.2=heb0550a_3
  - libtiff==4.1.0=h2733197_1
  - libstdcxx-ng==9.1.0=hdf63c60_0
  - libsodium==1.0.18=h36c2ea0_1
  - libpng==1.6.37=hbc83047_0
  - libgfortran4==7.5.0=hae1eefd_17
  - libgfortran-ng==7.5.0=hae1eefd_17
  - libgcc-ng==9.1.0=hdf63c60_0
  - libedit==3.1.20191231=h14c3975_1
  - ld_impl_linux-64==2.33.1=h53a641e_7
  - lcms2==2.11=h396b838_0
  - kiwisolver==1.3.1=py37hc928c03_0
  - jpeg==9b=h024ee3a_2
  - imagecodecs-lite==2019.12.3=py37h161383b_3
  - icu==67.1=he1b5a44_0
  - freetype==2.10.4=h5ab3b9f_0
  - cytoolz==0.11.0=py37h4abf009_1
  - cuda90==1.0=h6433d27_0
  - cryptography==3.3.1=py37h3c74f83_0
  - chardet==4.0.0=py37h89c1867_0
  - cffi==1.14.4=py37h261ae71_0
  - certifi==2020.12.5=py37h89c1867_1
  - brotlipy==0.7.0=py37hb5d75c8_1001
  - xz==5.2.5=h7b6447c_0
  - tk==8.6.10=hbc83047_0
  - setuptools==51.0.0=py37h06a4308_2
  - python==3.7.9=h7579374_0
  - pip==20.3.3=py37h06a4308_0
  - openssl==1.1.1k=h27cfd23_0
  - libffi==3.3=he6710b0_2
  - ca-certificates==2021.4.13=h06a4308_1

Current channels:

  - https://conda.anaconda.org/pytorch/win-64
  - https://conda.anaconda.org/conda-forge/win-64
  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/msys2/win-64

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

**Comment by jinyeying** [comment]
> conda env create -f shadow_env.yml
> 
> done Channels:
> 
> * pytorch
> * conda-forge
> * defaults
>   Platform: win-64
>   Collecting package metadata (repodata.json): done
>   Solving environment: failed
> 
> PackagesNotFoundError: The following packages are not available from current channels:
> 
> * zstd==1.4.5=h9ceee32_0
> * zlib==1.2.11=h7b6447c_3
> * zeromq==4.3.3=h58526e2_3
> * yaml==0.2.5=h516909a_0
> * websocket-client==0.57.0=py37h89c1867_3
> * tornado==6.1=py37h4abf009_0
> * torchvision==0.5.0=py37_cu100
> * sqlite==3.33.0=h62c20be_0
> * six==1.15.0=py37h06a4308_0
> * readline==8.0=h7b6447c_0
> * pyzmq==20.0.0=py37h5a562af_1
> * pyyaml==5.3.1=py37hb5d75c8_1
> * pywavelets==1.1.1=py37h161383b_3
> * pytorch==1.4.0=py3.7_cuda10.0.130_cudnn7.6.3_0
> * pysocks==1.7.1=py37he5f6b98_2
> * pillow==8.0.1=py37he98fc37_0
> * pathlib==1.0.1=py37h89c1867_4
> * ninja==1.10.2=py37hff7bd54_0
> * ncurses==6.2=he6710b0_1
> * mkl_random==1.1.1=py37h0573a6f_0
> * mkl_fft==1.2.0=py37h23d657b_0
> * mkl-service==2.3.0=py37he8ac12f_0
> * matplotlib-base==3.2.2=py37h1d35a4c_1
> * lz4-c==1.9.2=heb0550a_3
> * libtiff==4.1.0=h2733197_1
> * libstdcxx-ng==9.1.0=hdf63c60_0
> * libsodium==1.0.18=h36c2ea0_1
> * libpng==1.6.37=hbc83047_0
> * libgfortran4==7.5.0=hae1eefd_17
> * libgfortran-ng==7.5.0=hae1eefd_17
> * libgcc-ng==9.1.0=hdf63c60_0
> * libedit==3.1.20191231=h14c3975_1
> * ld_impl_linux-64==2.33.1=h53a641e_7
> * lcms2==2.11=h396b838_0
> * kiwisolver==1.3.1=py37hc928c03_0
> * jpeg==9b=h024ee3a_2
> * imagecodecs-lite==2019.12.3=py37h161383b_3
> * icu==67.1=he1b5a44_0
> * freetype==2.10.4=h5ab3b9f_0
> * cytoolz==0.11.0=py37h4abf009_1
> * cuda90==1.0=h6433d27_0
> * cryptography==3.3.1=py37h3c74f83_0
> * chardet==4.0.0=py37h89c1867_0
> * cffi==1.14.4=py37h261ae71_0
> * certifi==2020.12.5=py37h89c1867_1
> * brotlipy==0.7.0=py37hb5d75c8_1001
> * xz==5.2.5=h7b6447c_0
> * tk==8.6.10=hbc83047_0
> * setuptools==51.0.0=py37h06a4308_2
> * python==3.7.9=h7579374_0
> * pip==20.3.3=py37h06a4308_0
> * openssl==1.1.1k=h27cfd23_0
> * libffi==3.3=he6710b0_2
> * ca-certificates==2021.4.13=h06a4308_1
> 
> Current channels:
> 
> * https://conda.anaconda.org/pytorch/win-64
> * https://conda.anaconda.org/conda-forge/win-64
> * https://repo.anaconda.com/pkgs/main/win-64
> * https://repo.anaconda.com/pkgs/r/win-64
> * https://repo.anaconda.com/pkgs/msys2/win-64
> 
> To search for alternate channels that may provide the conda package you're looking for, navigate to
> 
> ```
> https://anaconda.org
> ```
> 
> and use the search bar at the top of the page.

hello 我是用Ubuntu环境的RTX 2080 Ti的server跑的

**Comment by jinyeying** [comment]
> conda env create -f shadow_env.yml
> 
> done Channels:
> 
> * pytorch
> * conda-forge
> * defaults
>   Platform: win-64
>   Collecting package metadata (repodata.json): done
>   Solving environment: failed
> 
> PackagesNotFoundError: The following packages are not available from current channels:
> 
> * zstd==1.4.5=h9ceee32_0
> * zlib==1.2.11=h7b6447c_3
> * zeromq==4.3.3=h58526e2_3
> * yaml==0.2.5=h516909a_0
> * websocket-client==0.57.0=py37h89c1867_3
> * tornado==6.1=py37h4abf009_0
> * torchvision==0.5.0=py37_cu100
> * sqlite==3.33.0=h62c20be_0
> * six==1.15.0=py37h06a4308_0
> * readline==8.0=h7b6447c_0
> * pyzmq==20.0.0=py37h5a562af_1
> * pyyaml==5.3.1=py37hb5d75c8_1
> * pywavelets==1.1.1=py37h161383b_3
> * pytorch==1.4.0=py3.7_cuda10.0.130_cudnn7.6.3_0
> * pysocks==1.7.1=py37he5f6b98_2
> * pillow==8.0.1=py37he98fc37_0
> * pathlib==1.0.1=py37h89c1867_4
> * ninja==1.10.2=py37hff7bd54_0
> * ncurses==6.2=he6710b0_1
> * mkl_random==1.1.1=py37h0573a6f_0
> * mkl_fft==1.2.0=py37h23d657b_0
> * mkl-service==2.3.0=py37he8ac12f_0
> * matplotlib-base==3.2.2=py37h1d35a4c_1
> * lz4-c==1.9.2=heb0550a_3
> * libtiff==4.1.0=h2733197_1
> * libstdcxx-ng==9.1.0=hdf63c60_0
> * libsodium==1.0.18=h36c2ea0_1
> * libpng==1.6.37=hbc83047_0
> * libgfortran4==7.5.0=hae1eefd_17
> * libgfortran-ng==7.5.0=hae1eefd_17
> * libgcc-ng==9.1.0=hdf63c60_0
> * libedit==3.1.20191231=h14c3975_1
> * ld_impl_linux-64==2.33.1=h53a641e_7
> * lcms2==2.11=h396b838_0
> * kiwisolver==1.3.1=py37hc928c03_0
> * jpeg==9b=h024ee3a_2
> * imagecodecs-lite==2019.12.3=py37h161383b_3
> * icu==67.1=he1b5a44_0
> * freetype==2.10.4=h5ab3b9f_0
> * cytoolz==0.11.0=py37h4abf009_1
> * cuda90==1.0=h6433d27_0
> * cryptography==3.3.1=py37h3c74f83_0
> * chardet==4.0.0=py37h89c1867_0
> * cffi==1.14.4=py37h261ae71_0
> * certifi==2020.12.5=py37h89c1867_1
> * brotlipy==0.7.0=py37hb5d75c8_1001
> * xz==5.2.5=h7b6447c_0
> * tk==8.6.10=hbc83047_0
> * setuptools==51.0.0=py37h06a4308_2
> * python==3.7.9=h7579374_0
> * pip==20.3.3=py37h06a4308_0
> * openssl==1.1.1k=h27cfd23_0
> * libffi==3.3=he6710b0_2
> * ca-certificates==2021.4.13=h06a4308_1
> 
> Current channels:
> 
> * https://conda.anaconda.org/pytorch/win-64
> * https://conda.anaconda.org/conda-forge/win-64
> * https://repo.anaconda.com/pkgs/main/win-64
> * https://repo.anaconda.com/pkgs/r/win-64
> * https://repo.anaconda.com/pkgs/msys2/win-64
> 
> To search for alternate channels that may provide the conda package you're looking for, navigate to
> 
> ```
> https://anaconda.org
> ```
> 
> and use the search bar at the top of the page.

https://medium.com/@huchi00057/%E5%9C%96%E6%96%87%E6%95%99%E5%AD%B8-dc-shadownet-%E6%89%8B%E6%8A%8A%E6%89%8B%E5%B8%B6%E4%BD%A0%E5%81%9A-d2ec03495585

You can follow the above link.

**Comment by HIHHIYAYAYOO** [comment]
> > conda env create -f shadow_env.yml
> > done Channels:
> > 
> > * pytorch
> > * conda-forge
> > * defaults
> >   Platform: win-64
> >   Collecting package metadata (repodata.json): done
> >   Solving environment: failed
> > 
> > PackagesNotFoundError: The following packages are not available from current channels:
> > 
> > * zstd==1.4.5=h9ceee32_0
> > * zlib==1.2.11=h7b6447c_3
> > * zeromq==4.3.3=h58526e2_3
> > * yaml==0.2.5=h516909a_0
> > * websocket-client==0.57.0=py37h89c1867_3
> > * tornado==6.1=py37h4abf009_0
> > * torchvision==0.5.0=py37_cu100
> > * sqlite==3.33.0=h62c20be_0
> > * six==1.15.0=py37h06a4308_0
> > * readline==8.0=h7b6447c_0
> > * pyzmq==20.0.0=py37h5a562af_1
> > * pyyaml==5.3.1=py37hb5d75c8_1
> > * pywavelets==1.1.1=py37h161383b_3
> > * pytorch==1.4.0=py3.7_cuda10.0.130_cudnn7.6.3_0
> > * pysocks==1.7.1=py37he5f6b98_2
> > * pillow==8.0.1=py37he98fc37_0
> > * pathlib==1.0.1=py37h89c1867_4
> > * ninja==1.10.2=py37hff7bd54_0
> > * ncurses==6.2=he6710b0_1
> > * mkl_random==1.1.1=py37h0573a6f_0
> > * mkl_fft==1.2.0=py37h23d657b_0
> > * mkl-service==2.3.0=py37he8ac12f_0
> > * matplotlib-base==3.2.2=py37h1d35a4c_1
> > * lz4-c==1.9.2=heb0550a_3
> > * libtiff==4.1.0=h2733197_1
> > * libstdcxx-ng==9.1.0=hdf63c60_0
> > * libsodium==1.0.18=h36c2ea0_1
> > * libpng==1.6.37=hbc83047_0
> > * libgfortran4==7.5.0=hae1eefd_17
> > * libgfortran-ng==7.5.0=hae1eefd_17
> > * libgcc-ng==9.1.0=hdf63c60_0
> > * libedit==3.1.20191231=h14c3975_1
> > * ld_impl_linux-64==2.33.1=h53a641e_7
> > * lcms2==2.11=h396b838_0
> > * kiwisolver==1.3.1=py37hc928c03_0
> > * jpeg==9b=h024ee3a_2
> > * imagecodecs-lite==2019.12.3=py37h161383b_3
> > * icu==67.1=he1b5a44_0
> > * freetype==2.10.4=h5ab3b9f_0
> > * cytoolz==0.11.0=py37h4abf009_1
> > * cuda90==1.0=h6433d27_0
> > * cryptography==3.3.1=py37h3c74f83_0
> > * chardet==4.0.0=py37h89c1867_0
> > * cffi==1.14.4=py37h261ae71_0
> > * certifi==2020.12.5=py37h89c1867_1
> > * brotlipy==0.7.0=py37hb5d75c8_1001
> > * xz==5.2.5=h7b6447c_0
> > * tk==8.6.10=hbc83047_0
> > * setuptools==51.0.0=py37h06a4308_2
> > * python==3.7.9=h7579374_0
> > * pip==20.3.3=py37h06a4308_0
> > * openssl==1.1.1k=h27cfd23_0
> > * libffi==3.3=he6710b0_2
> > * ca-certificates==2021.4.13=h06a4308_1
> > 
> > Current channels:
> > 
> > * https://conda.anaconda.org/pytorch/win-64
> > * https://conda.anaconda.org/conda-forge/win-64
> > * https://repo.anaconda.com/pkgs/main/win-64
> > * https://repo.anaconda.com/pkgs/r/win-64
> > * https://repo.anaconda.com/pkgs/msys2/win-64
> > 
> > To search for alternate channels that may provide the conda package you're looking for, navigate to
> > ```
> > https://anaconda.org
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and use the search bar at the top of the page.
> 
> hello 我是用Ubuntu环境的RTX 2080 Ti的server跑的


以下為替換後的系統:
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.6 LTS
Release:        20.04
Codename:       focal

換作業系統後變成以下問題:
$ conda env create -f shadow_env.yml
Collecting package metadata (repodata.json): \ WARNING conda.models.version:get_matcher(535): Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 1.7.1.*, but conda is ignoring the .* and treating it as 1.7.1
WARNING conda.models.version:get_matcher(535): Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 1.8.0.*, but conda is ignoring the .* and treating it as 1.8.0
WARNING conda.models.version:get_matcher(535): Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 1.9.0.*, but conda is ignoring the .* and treating it as 1.9.0
WARNING conda.models.version:get_matcher(535): Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 1.6.0.*, but conda is ignoring the .* and treating it as 1.6.0                                        done
Solving environment: failed

ResolvePackageNotFound:
  - pytorch==1.4.0=py3.7_cuda10.0.130_cudnn7.6.3_0
  - torchvision==0.5.0=py37_cu100

**Comment by jinyeying** [comment]
写着问题呢呀 安装一下环境 pytorch==1.4.0=py3.7_cuda10.0.130_cudnn7.6.3_0
torchvision==0.5.0=py37_cu100

**Comment by HIHHIYAYAYOO** [comment]
> 写着问题呢呀 安装一下环境 pytorch==1.4.0=py3.7_cuda10.0.130_cudnn7.6.3_0 torchvision==0.5.0=py37_cu100

不是 conda 當前 channels 無法找到特定版本的 pytorch 和 torchvision 嗎?
抱歉不是很熟悉 Anaconda🙏🙏🙏

**Comment by jinyeying** [comment]
> > 写着问题呢呀 安装一下环境 pytorch==1.4.0=py3.7_cuda10.0.130_cudnn7.6.3_0 torchvision==0.5.0=py37_cu100
> 
> 不是 conda 當前 channels 無法找到特定版本的 pytorch 和 torchvision 嗎? 抱歉不是很熟悉 Anaconda🙏🙏🙏

【AI 夜间图像增强（再黑也能看见）-哔哩哔哩】 https://b23.tv/r9hIhrv
可以看下b站这个教程，我的另外一个工作。环境和这个差不多。

**Comment by jinyeying** [comment]
> > 写着问题呢呀 安装一下环境 pytorch==1.4.0=py3.7_cuda10.0.130_cudnn7.6.3_0 torchvision==0.5.0=py37_cu100
> 
> 不是 conda 當前 channels 無法找到特定版本的 pytorch 和 torchvision 嗎? 抱歉不是很熟悉 Anaconda🙏🙏🙏

我更新了如何建立环境，We test the code on PyTorch 1.10.2 + CUDA 11.3 + cuDNN 8.2.0.
git clone https://github.com/jinyeying/DC-ShadowNet-Hard-and-Soft-Shadow-Removal.git
cd DC-ShadowNet-Hard-and-Soft-Shadow-Removal/
conda create -n shadow python=3.7
conda activate shadow
conda install pytorch=1.10.2 torchvision torchaudio cudatoolkit=11.3 -c pytorch
python3 -m pip install -r requirements.txt
