### ISSUE TITLE
单张图片的测试

### ISSUE THREAD

**Issue by Jasonx0123** [jinyeying/DC-ShadowNet-Hard-and-Soft-Shadow-Removal#29]
请问下可以实现其他图片的阴影去除测试吗？

**Comment by jinyeying** [comment]
> 请问下可以实现其他图片的阴影去除测试吗？

可以啊，你试试

**Comment by Jasonx0123** [comment]
请问测试的话也是用main_test.py吗？我把我的图片放在了指定路径下，运行
python maitest.py --dataset SRD --datasetpath /home/psdz/sym/Dc-ShadowNet-Hard-and-Softshadow-Removal-main/test/--use original name False后没有保存去阴影后的结果，但是有test finished

**Comment by jinyeying** [comment]
> 请问测试的话也是用main_test.py吗？我把我的图片放在了指定路径下，运行 python maitest.py --dataset SRD --datasetpath /home/psdz/sym/Dc-ShadowNet-Hard-and-Softshadow-Removal-main/test/--use original name False后没有保存去阴影后的结果，但是有test finished

是的，可以参考下 https://medium.com/@huchi00057/%E5%9C%96%E6%96%87%E6%95%99%E5%AD%B8-dc-shadownet-%E6%89%8B%E6%8A%8A%E6%89%8B%E5%B8%B6%E4%BD%A0%E5%81%9A-d2ec03495585
里面有教程教你测试。

**Comment by jinyeying** [comment]
> 请问测试的话也是用main_test.py吗？我把我的图片放在了指定路径下，运行 python maitest.py --dataset SRD --datasetpath /home/psdz/sym/Dc-ShadowNet-Hard-and-Softshadow-Removal-main/test/--use original name False后没有保存去阴影后的结果，但是有test finished
我大概知道你的意思了，试试 python main_test_single.py
[Update main_test_single.py and DCShadowNet_test_single.py]
Put the test images in test_input, results in: results/output/ results/input_output/

**Comment by Jasonshao0123** [comment]
> > 请问测试的话也是用main_test.py吗？我把我的图片放在了指定路径下，运行 python maitest.py --dataset SRD --datasetpath /home/psdz/sym/Dc-ShadowNet-Hard-and-Softshadow-Removal-main/test/--use original name False后没有保存去阴影后的结果，但是有test finished
> > 我大概知道你的意思了，试试 python main_test_single.py
> > [Update main_test_single.py and DCShadowNet_test_single.py]
> > Put the test images in test_input, results in: results/output/ results/input_output/

谢谢回复哈，请问下我在运行main_test_single.py时，是不是应该请提前把模型权重放到result里面对应的数据集类别里面呢？还想再请教个问题，如果只有阴影图像和阴影mask二值图像，没有无阴影GT图像，可以实现阴影去除吗？

**Comment by Jasonx0123** [comment]
> > 请问测试的话也是用main_test.py吗？我把我的图片放在了指定路径下，运行 python maitest.py --dataset SRD --datasetpath /home/psdz/sym/Dc-ShadowNet-Hard-and-Softshadow-Removal-main/test/--use original name False后没有保存去阴影后的结果，但是有test finished
> > 我大概知道你的意思了，试试 python main_test_single.py
> > [Update main_test_single.py and DCShadowNet_test_single.py]
> > Put the test images in test_input, results in: results/output/ results/input_output/

谢谢大神的回复，还想再请教个问题，请问如果只有阴影图像和阴影mask二值图像，没有无阴影GT图像，可以实现阴影去除吗？目前研究方向为交通场景的阴影去除，目前只找到了CUHK Shadow这个数据集，里面只有阴影图像和阴影mask图像，没有找到其他数据集，不知道应该怎么做下去了

**Comment by jinyeying** [comment]
> > > 请问测试的话也是用main_test.py吗？我把我的图片放在了指定路径下，运行 python maitest.py --dataset SRD --datasetpath /home/psdz/sym/Dc-ShadowNet-Hard-and-Softshadow-Removal-main/test/--use original name False后没有保存去阴影后的结果，但是有test finished
> > > 我大概知道你的意思了，试试 python main_test_single.py
> > > [Update main_test_single.py and DCShadowNet_test_single.py]
> > > Put the test images in test_input, results in: results/output/ results/input_output/
> 
> 谢谢大神的回复，还想再请教个问题，请问如果只有阴影图像和阴影mask二值图像，没有无阴影GT图像，可以实现阴影去除吗？目前研究方向为交通场景的阴影去除，目前只找到了CUHK Shadow这个数据集，里面只有阴影图像和阴影mask图像，没有找到其他数据集，不知道应该怎么做下去了

可以拿其他dataset上pre-trainded的模型试试看
