### ISSUE TITLE
DCShadowNet_train.py  seems not exist

### ISSUE THREAD

**Issue by howardgriffin** [jinyeying/DC-ShadowNet-Hard-and-Soft-Shadow-Removal#3]
Nice work! But I cannot find the DCShadowNet_train.py, would you plan to release it?

**Comment by jinyeying** [comment]
Thank you for your interest. We are working on cleaning the code and will provide it once finished. Please stay tuned.

**Comment by jinyeying** [comment]
> Nice work! But I cannot find the DCShadowNet_train.py, would you plan to release it?

Thank you for your interest. We are working on cleaning the code and will provide it once finished. Please stay tuned.

**Comment by nachifur** [comment]
I have the same problem. Is this problem solved? @howardgriffin @jinyeying 
Thank you for your reply!

**Comment by jinyeying** [comment]
> I have the same problem. Is this problem solved? @howardgriffin @jinyeying Thank you for your reply!

We have released the training code.
