### ISSUE TITLE
请问作者，我如果要训练自己的数据集，该如何准备呢？

### ISSUE THREAD

**Issue by swjtuer0762** [jinyeying/DC-ShadowNet-Hard-and-Soft-Shadow-Removal#32]

**Comment by jinyeying** [comment]
自己的影子数据集么？有物体在么？

**Comment by jinyeying** [comment]
> _No description provided._

具体说说你是要自己收集自己的数据集，还是训练自己的数据集？

**Comment by swjtuer0762** [comment]
首先是收集自己的数据集，然后再训练，这两个步骤我都有一些疑问，首先我不知道自己的图片是否符合标准，以下是我的图片。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年5月27日(周一) 中午11:41
收件人: ***@***.***&gt;;
抄送: "Zeng ***@***.******@***.***&gt;;
主题: Re: [jinyeying/DC-ShadowNet-Hard-and-Soft-Shadow-Removal] 请问作者，我如果要训练自己的数据集，该如何准备呢？ (Issue #32)




  
No description provided.
  
具体说说你是要自己收集自己的数据集，还是训练自己的数据集？

**Comment by jinyeying** [comment]
<img width="839" alt="dataset" src="https://github.com/jinyeying/DC-ShadowNet-Hard-and-Soft-Shadow-Removal/assets/36725804/57b4464c-2bd3-4b13-8283-6f3c8fa4725c">
看不到你的图，follow [1] DeshadowNet: A Multi-Context Embedding Deep Network for Shadow Removal. CVPR 2017
[2] Shadow removal via shadow image decomposition. ICCV 2019 收集数据就好了

**Comment by swjtuer0762** [comment]
![001](https://github.com/jinyeying/DC-ShadowNet-Hard-and-Soft-Shadow-Removal/assets/103750314/7176b0c2-7ec6-47d5-b88e-9120daaf0765)
![001](https://github.com/jinyeying/DC-ShadowNet-Hard-and-Soft-Shadow-Removal/assets/103750314/546d341d-c9db-4e0b-9cc6-6281924c301d)
我重新发送一下，像这样，圆形靶标的边缘会存在一些影子。

**Comment by jinyeying** [comment]
> ![001](https://private-user-images.githubusercontent.com/103750314/333956671-7176b0c2-7ec6-47d5-b88e-9120daaf0765.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyNDc0ODYsIm5iZiI6MTcxNzI0NzE4NiwicGF0aCI6Ii8xMDM3NTAzMTQvMzMzOTU2NjcxLTcxNzZiMGMyLTdlYzYtNDdkNS1iODhlLTkxMjBkYWFmMDc2NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwMVQxMzA2MjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNGU1Y2Y4NTdkYmU3NWY2NDBmNjA1YzI0NTNiNTZlNWJkZDY2OTZkMGU2ZmNlZDJiYTQxMjhjY2M4NTFmYmE1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._Y-9pA1oaUD3rfMYTOz4HC06HVlH-weo2UI27sx8vss) ![001](https://private-user-images.githubusercontent.com/103750314/333956816-546d341d-c9db-4e0b-9cc6-6281924c301d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyNDc0ODYsIm5iZiI6MTcxNzI0NzE4NiwicGF0aCI6Ii8xMDM3NTAzMTQvMzMzOTU2ODE2LTU0NmQzNDFkLWM5ZGItNGUwYi05Y2M2LTYyODE5MjRjMzAxZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwMVQxMzA2MjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03YjUxZGE5MzgyOWEwM2NhYTJmMWU5MzMwODBiYWRkZjAzMDE2NThjZDFhZGVkMmY4ZmQ1OTc4YTFhOGMwMjMzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.TiKXER3E-z3yarHGOu3EJaI7OOMSKehsGUvinbylZaE) 我重新发送一下，像这样，圆形靶标的边缘会存在一些影子。

你这个不对吧，都是有影子的

**Comment by swjtuer0762** [comment]
也就是说还要有对应的无影子的图片，可我没办法拍到这样的图。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年6月1日(周六) 晚上9:07
收件人: ***@***.***&gt;;
抄送: "Zeng ***@***.******@***.***&gt;;
主题: Re: [jinyeying/DC-ShadowNet-Hard-and-Soft-Shadow-Removal] 请问作者，我如果要训练自己的数据集，该如何准备呢？ (Issue #32)




  
  我重新发送一下，像这样，圆形靶标的边缘会存在一些影子。
  
你这个不对吧，都是有影子的

**Comment by jinyeying** [comment]
> 也就是说还要有对应的无影子的图片，可我没办法拍到这样的图。
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年6月1日(周六) 晚上9:07 收件人: ***@***.***&gt;; 抄送: "Zeng ***@***.******@***.***&gt;; 主题: Re: [jinyeying/DC-ShadowNet-Hard-and-Soft-Shadow-Removal] 请问作者，我如果要训练自己的数据集，该如何准备呢？ (Issue #32) 我重新发送一下，像这样，圆形靶标的边缘会存在一些影子。 你这个不对吧，都是有影子的 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

所以说自阴影很难啊，可以看下我们AAAI‘24的DeS3: Adaptive Attention-driven Self and Soft Shadow Removal using ViT Similarity

**Comment by smart4654154** [comment]
> > 也就是说还要有对应的无影子的图片，可我没办法拍到这样的图。
> > […](#)
> > ---原始邮件--- 发件人: _**@**_._**> 发送时间: 2024年6月1日(周六) 晚上9:07 收件人: _**@**_.**_>; 抄送: "Zeng _**@**_._**_**@**_.**_>; 主题: Re: [jinyeying/DC-ShadowNet-Hard-and-Soft-Shadow-Removal] 请问作者，我如果要训练自己的数据集，该如何准备呢？ (Issue #32) 我重新发送一下，像这样，圆形靶标的边缘会存在一些影子。 你这个不对吧，都是有影子的 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: _**@**_.***>
> 
> 所以说自阴影很难啊，可以看下我们AAAI‘24的DeS3: Adaptive Attention-driven Self and Soft Shadow Removal using ViT Similarity



作者你好，现在我有一份无人机拍摄的数据，因为光线原因，有楼的阴影（无法提供无阴影的数据），我想去除，所以看到了这篇无监督去阴影的文章，但是看到这个issue，这个文章无法做到直接去除一张图像的阴影？谢谢

**Comment by swjtuer0762** [comment]
我建议你可以关注一下“显著性目标检测”这个领域，当时我也想用阴影去除的算法解决我的问题，后面我发现“显著性目标检测”是更好的选择，比如U^2Net网络，你可以去了解了解。



---原始邮件---
发件人: "Zhilong ***@***.***&gt;
发送时间: 2024年9月18日(周三) 晚上7:59
收件人: ***@***.***&gt;;
抄送: "Zeng ***@***.******@***.***&gt;;
主题: Re: [jinyeying/DC-ShadowNet-Hard-and-Soft-Shadow-Removal] 请问作者，我如果要训练自己的数据集，该如何准备呢？ (Issue #32)




   
也就是说还要有对应的无影子的图片，可我没办法拍到这样的图。
 …
 ---原始邮件--- 发件人: @.&gt; 发送时间: 2024年6月1日(周六) 晚上9:07 收件人: _@**._&gt;; 抄送: "Zeng ***@***.***@._&gt;; 主题: Re: [jinyeying/DC-ShadowNet-Hard-and-Soft-Shadow-Removal] 请问作者，我如果要训练自己的数据集，该如何准备呢？ (Issue #32) 我重新发送一下，像这样，圆形靶标的边缘会存在一些影子。 你这个不对吧，都是有影子的 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: _@_.*&gt;
  
所以说自阴影很难啊，可以看下我们AAAI‘24的DeS3: Adaptive Attention-driven Self and Soft Shadow Removal using ViT Similarity
  
作者你好，现在我有一份无人机拍摄的数据，因为光线原因，有楼的阴影（无法提供无阴影的数据），我想去除，所以看到了这篇无监督去阴影的文章，但是看到这个issue，这个文章无法做到直接去除一张图像的阴影？谢谢

**Comment by swjtuer0762** [comment]
我的任务是：把目标从背景中分离出来。
当时我遇到的问题是目标周围的阴影和目标本身很接近，所以很难分开，当时就想着阴影去除，不过后面就用了U^2Net，直接解决问题。



---原始邮件---
发件人: "Zhilong ***@***.***&gt;
发送时间: 2024年9月18日(周三) 晚上7:59
收件人: ***@***.***&gt;;
抄送: "Zeng ***@***.******@***.***&gt;;
主题: Re: [jinyeying/DC-ShadowNet-Hard-and-Soft-Shadow-Removal] 请问作者，我如果要训练自己的数据集，该如何准备呢？ (Issue #32)




   
也就是说还要有对应的无影子的图片，可我没办法拍到这样的图。
 …
 ---原始邮件--- 发件人: @.&gt; 发送时间: 2024年6月1日(周六) 晚上9:07 收件人: _@**._&gt;; 抄送: "Zeng ***@***.***@._&gt;; 主题: Re: [jinyeying/DC-ShadowNet-Hard-and-Soft-Shadow-Removal] 请问作者，我如果要训练自己的数据集，该如何准备呢？ (Issue #32) 我重新发送一下，像这样，圆形靶标的边缘会存在一些影子。 你这个不对吧，都是有影子的 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: _@_.*&gt;
  
所以说自阴影很难啊，可以看下我们AAAI‘24的DeS3: Adaptive Attention-driven Self and Soft Shadow Removal using ViT Similarity
  
作者你好，现在我有一份无人机拍摄的数据，因为光线原因，有楼的阴影（无法提供无阴影的数据），我想去除，所以看到了这篇无监督去阴影的文章，但是看到这个issue，这个文章无法做到直接去除一张图像的阴影？谢谢

**Comment by smart4654154** [comment]
> 我建议你可以关注一下“显著性目标检测”这个领域，当时我也想用阴影去除的算法解决我的问题，后面我发现“显著性目标检测”是更好的选择，比如U^2Net网络，你可以去了解了解。
> […](#)
> ---原始邮件--- 发件人: "Zhilong ***@***.***&gt; 发送时间: 2024年9月18日(周三) 晚上7:59 收件人: ***@***.***&gt;; 抄送: "Zeng ***@***.******@***.***&gt;; 主题: Re: [jinyeying/DC-ShadowNet-Hard-and-Soft-Shadow-Removal] 请问作者，我如果要训练自己的数据集，该如何准备呢？ (Issue #32) 也就是说还要有对应的无影子的图片，可我没办法拍到这样的图。 … ---原始邮件--- 发件人: @.&gt; 发送时间: 2024年6月1日(周六) 晚上9:07 收件人: _@**._&gt;; 抄送: "Zeng ***@***.***@._&gt;; 主题: Re: [jinyeying/DC-ShadowNet-Hard-and-Soft-Shadow-Removal] 请问作者，我如果要训练自己的数据集，该如何准备呢？ (Issue #32) 我重新发送一下，像这样，圆形靶标的边缘会存在一些影子。 你这个不对吧，都是有影子的 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: _@_.*&gt; 所以说自阴影很难啊，可以看下我们AAAI‘24的DeS3: Adaptive Attention-driven Self and Soft Shadow Removal using ViT Similarity 作者你好，现在我有一份无人机拍摄的数据，因为光线原因，有楼的阴影（无法提供无阴影的数据），我想去除，所以看到了这篇无监督去阴影的文章，但是看到这个issue，这个文章无法做到直接去除一张图像的阴影？谢谢 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

谢谢我的需求就是对照片去除影子，把去影子的照片拿去做深度学习，我不需要提取物体，我认为去阴影是最佳的

**Comment by jinyeying** [comment]
> 我有一份无人机拍摄的数据，因为光线原因，有楼的阴影（无法提供无阴影的数据），我想去除，所以看到了这篇无监督去阴影的文章，但是看到这个issue，这个文章无法做到直接去除一张图像的阴影？谢谢

这篇是无监督的,用的是cyclegan-based的网络,准备两个domain的数据,一个domain有阴影,一个domain没阴影,domain gap不要太大,就可以训练了

**Comment by jinyeying** [comment]
> 我的任务是：把目标从背景中分离出来。 当时我遇到的问题是目标周围的阴影和目标本身很接近，所以很难分开，当时就想着阴影去除，不过后面就用了U^2Net，直接解决问题。
> […](#)
> ---原始邮件--- 发件人: "Zhilong ***@***.***&gt; 发送时间: 2024年9月18日(周三) 晚上7:59 收件人: ***@***.***&gt;; 抄送: "Zeng ***@***.******@***.***&gt;; 主题: Re: [jinyeying/DC-ShadowNet-Hard-and-Soft-Shadow-Removal] 请问作者，我如果要训练自己的数据集，该如何准备呢？ (Issue #32) 也就是说还要有对应的无影子的图片，可我没办法拍到这样的图。 … ---原始邮件--- 发件人: @.&gt; 发送时间: 2024年6月1日(周六) 晚上9:07 收件人: _@**._&gt;; 抄送: "Zeng ***@***.***@._&gt;; 主题: Re: [jinyeying/DC-ShadowNet-Hard-and-Soft-Shadow-Removal] 请问作者，我如果要训练自己的数据集，该如何准备呢？ (Issue #32) 我重新发送一下，像这样，圆形靶标的边缘会存在一些影子。 你这个不对吧，都是有影子的 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: _@_.*&gt; 所以说自阴影很难啊，可以看下我们AAAI‘24的DeS3: Adaptive Attention-driven Self and Soft Shadow Removal using ViT Similarity 作者你好，现在我有一份无人机拍摄的数据，因为光线原因，有楼的阴影（无法提供无阴影的数据），我想去除，所以看到了这篇无监督去阴影的文章，但是看到这个issue，这个文章无法做到直接去除一张图像的阴影？谢谢 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

强的啊

**Comment by swjtuer0762** [comment]
没有对应的无影子图片，这个就很难搞😂



---原始邮件---
发件人: "Zhilong ***@***.***&gt;
发送时间: 2024年9月18日(周三) 晚上7:59
收件人: ***@***.***&gt;;
抄送: "Zeng ***@***.******@***.***&gt;;
主题: Re: [jinyeying/DC-ShadowNet-Hard-and-Soft-Shadow-Removal] 请问作者，我如果要训练自己的数据集，该如何准备呢？ (Issue #32)




   
也就是说还要有对应的无影子的图片，可我没办法拍到这样的图。
 …
 ---原始邮件--- 发件人: @.&gt; 发送时间: 2024年6月1日(周六) 晚上9:07 收件人: _@**._&gt;; 抄送: "Zeng ***@***.***@._&gt;; 主题: Re: [jinyeying/DC-ShadowNet-Hard-and-Soft-Shadow-Removal] 请问作者，我如果要训练自己的数据集，该如何准备呢？ (Issue #32) 我重新发送一下，像这样，圆形靶标的边缘会存在一些影子。 你这个不对吧，都是有影子的 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: _@_.*&gt;
  
所以说自阴影很难啊，可以看下我们AAAI‘24的DeS3: Adaptive Attention-driven Self and Soft Shadow Removal using ViT Similarity
  
作者你好，现在我有一份无人机拍摄的数据，因为光线原因，有楼的阴影（无法提供无阴影的数据），我想去除，所以看到了这篇无监督去阴影的文章，但是看到这个issue，这个文章无法做到直接去除一张图像的阴影？谢谢

**Comment by smart4654154** [comment]
> > 我有一份无人机拍摄的数据，因为光线原因，有楼的阴影（无法提供无阴影的数据），我想去除，所以看到了这篇无监督去阴影的文章，但是看到这个issue，这个文章无法做到直接去除一张图像的阴影？谢谢
> 
> 这篇是无监督的,用的是cyclegan-based的网络,准备两个domain的数据,一个domain有阴影,一个domain没阴影,domain gap不要太大,就可以训练了

十分感谢回复，我不太理解您回复中的无监督。我理解中的无监督是给出有阴影的数据，无需对应的无阴影数据，即可实现去除阴影。
信息来自这篇综述：Unveiling Deep Shadows: A Survey on Image and Video Shadow Detection, Removal, and Generation in the Era of Deep Learning
![image](https://github.com/user-attachments/assets/40a9e9e5-6769-4c22-a376-fea8a367b5f7)

但是参考您的回复，无监督模型还是需要给出有阴影的数据和对应的无阴影数据。
想请您具体解释一下。
用时请您推荐一下给出有阴影的数据，无需对应的无阴影数据，即可实现去除阴影的算法
十分感谢

**Comment by jinyeying** [comment]
> 监督

你可以看下USR数据集，有阴影的数据和对应的无阴影数据是不配对的

**Comment by jinyeying** [comment]
> > > 我有一份无人机拍摄的数据，因为光线原因，有楼的阴影（无法提供无阴影的数据），我想去除，所以看到了这篇无监督去阴影的文章，但是看到这个issue，这个文章无法做到直接去除一张图像的阴影？谢谢
> > 
> > 
> > 这篇是无监督的,用的是cyclegan-based的网络,准备两个domain的数据,一个domain有阴影,一个domain没阴影,domain gap不要太大,就可以训练了
> 
> 十分感谢回复，我不太理解您回复中的无监督。我理解中的无监督是给出有阴影的数据，无需对应的无阴影数据，即可实现去除阴影。 信息来自这篇综述：Unveiling Deep Shadows: A Survey on Image and Video Shadow Detection, Removal, and Generation in the Era of Deep Learning ![image](https://private-user-images.githubusercontent.com/152783898/368867071-40a9e9e5-6769-4c22-a376-fea8a367b5f7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3Mjc5NzAsIm5iZiI6MTcyNjcyNzY3MCwicGF0aCI6Ii8xNTI3ODM4OTgvMzY4ODY3MDcxLTQwYTllOWU1LTY3NjktNGMyMi1hMzc2LWZlYThhMzY3YjVmNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxOVQwNjM0MzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNmE5NjYyNjJlNmIyZmEwY2FmNGM0YTRmODhlZDYxNDQzOWZjMDE5NjRmZjk5OTVkMzI2NDY1M2ExZWYzYTI2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.avQGMlGExCmYjPuRcaIj1ZsS-Rt_V6LpiGj49oAG-zk)
> 
> 但是参考您的回复，无监督模型还是需要给出有阴影的数据和对应的无阴影数据。 想请您具体解释一下。 用时请您推荐一下给出有阴影的数据，无需对应的无阴影数据，即可实现去除阴影的算法 十分感谢
Mask-ShadowGAN，这里有USR Dataset，DC-ShadowNet和Mask-ShadowGAN的实验setting是一样的。
https://github.com/xw-hu/Mask-ShadowGAN
