### ISSUE TITLE
关于SRD数据集

### ISSUE THREAD

**Issue by Cloudjoker** [jinyeying/DC-ShadowNet-Hard-and-Soft-Shadow-Removal#33]
你好，我发现链接中SRD数据集test中阴影图片和mask有几张图片不一致，您能提供初始的SRD数据集的test吗，谢谢

**Comment by jinyeying** [comment]
原始SRD数据集test是没有mask的，都是大家自己提取的

**Comment by Cloudjoker** [comment]
> 原始SRD数据集test是没有mask的，都是大家自己提取的
我的意思是DHAN提供的SRD的test的mask和阴影图像有几张没有对应，尺寸也不一样。
![屏幕截图 2024-06-07 094624](https://github.com/jinyeying/DC-ShadowNet-Hard-and-Soft-Shadow-Removal/assets/106307007/7582c10f-370d-4c9b-9cb2-56be566575ac)

**Comment by Cloudjoker** [comment]
这些图片test中没有，同时mask中也缺了几张对应的图片

**Comment by jinyeying** [comment]
> 这些图片test中没有，同时mask中也缺了几张对应的图片

你是说我给的SRD test出了问题？还是DHAN的mask？

**Comment by jinyeying** [comment]
> > 原始SRD数据集test是没有mask的，都是大家自己提取的
> > 我的意思是DHAN提供的SRD的test的mask和阴影图像有几张没有对应，尺寸也不一样。
> > ![屏幕截图 2024-06-07 094624](https://private-user-images.githubusercontent.com/106307007/337494181-7582c10f-370d-4c9b-9cb2-56be566575ac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzNjk4OTYsIm5iZiI6MTcxOTM2OTU5NiwicGF0aCI6Ii8xMDYzMDcwMDcvMzM3NDk0MTgxLTc1ODJjMTBmLTM3MGQtNGM5Yi05Y2IyLTU2YmU1NjY1NzVhYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyNlQwMjM5NTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZGJiMjM4NjczNzE5YzI4YjI5ZWE3MDU3MDhiMTNiYzlmMmUxZjRkYzg1NGJiNzM0NzEzODY3MTZlYWU2MDUyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.mj8F6qdnBvJTXT8PBK5vlxHVFHNaCe0he4CAQe2wv-c)

我evaluate用的256的size，可以看看。链接：https://pan.baidu.com/s/17arAOvTs8DzQFdwqAl7ZwA?pwd=4hcv，提取码：4hcv

**Comment by Cloudjoker** [comment]
非常感谢

**Comment by ruchu001** [comment]
我也遇到了同样的问题
