### ISSUE TITLE
LRSS dataset cannot download

### ISSUE THREAD

**Issue by Xinrui014** [jinyeying/DC-ShadowNet-Hard-and-Soft-Shadow-Removal#34]
Hi, thank you for your work!

I am looking for the LRSS dataset, but I am unable to download the dataset containing 134 shadow images from the link you provided. Could you please share the LRSS dataset via an online Drive?

Thank you!

**Comment by jinyeying** [comment]
> Hi, thank you for your work!
> 
> I am looking for the LRSS dataset, but I am unable to download the dataset containing 134 shadow images from the link you provided. Could you please share the LRSS dataset via an online Drive?
> 
> Thank you!

http://visual.cs.ucl.ac.uk/pubs/softshadows/img/real97.html 里面有影子和ground truth的图

**Comment by Xinrui014** [comment]
非常感谢！

**Comment by Siriwangxr** [comment]
Hi, 请问可以提供一下LRSS training/testing set 吗，您在paper里只说了划分34张做training, 但是似乎没有release具体的划分方法。非常感谢

**Comment by Xinrui014** [comment]
hi, 请问可以提供一下LRSS的testing image ID么，论文里您提到把134张图划分成了100/34， 但是似乎并没有提到是如何划分的。我从LRSS的官网下载到的 shadow-shadow_free pair 有61对。

**Comment by jinyeying** [comment]
> hi, 请问可以提供一下LRSS的testing image ID么，论文里您提到把134张图划分成了100/34， 但是似乎并没有提到是如何划分的。我从LRSS的官网下载到的 shadow-shadow_free pair 有61对。

hi，我更新了下，加了链接

**Comment by Xinrui014** [comment]
非常感谢您的帮助！
