### ISSUE TITLE
evaluation

### ISSUE THREAD

**Issue by Halfpoint1** [jinyeying/DC-ShadowNet-Hard-and-Soft-Shadow-Removal#4]
Sorry to interrupt you, I want to ask you some questions. Is the RMSE index of the input image of the ISTD+ dataset in your paper measured with your matlab code? I tested different results, and I am confused about the evaluation indicators. I hope you can help me answer my doubts, thank you.

**Comment by jinyeying** [comment]
Yes, I double-checked, the number is correct.

SRD Dataset set the paths of the shadow removal result and the dataset in demo_srd_release.m and then run it.
Get the following Table 1 in the main paper on the SRD (size: 256x256).

**Comment by jinyeying** [comment]
> Sorry to interrupt you, I want to ask you some questions. Is the RMSE index of the input image of the ISTD+ dataset in your paper measured with your matlab code? I tested different results, and I am confused about the evaluation indicators. I hope you can help me answer my doubts, thank you.

Yes, I double-checked, the number is correct.

SRD Dataset set the paths of the shadow removal result and the dataset in demo_srd_release.m and then run it.
Get the following Table 1 in the main paper on the SRD (size: 256x256).

**Comment by Halfpoint1** [comment]
How about AISTD?&nbsp;Can you add me to QQ if it is convenient? My QQ number is ’995812609’.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jinyeying/DC-ShadowNet-Hard-and-Soft-Shadow-Removal"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月6日(星期四) 上午10:40
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jinyeying/DC-ShadowNet-Hard-and-Soft-Shadow-Removal] evaluation (Issue #4)





  
Sorry to interrupt you, I want to ask you some questions. Is the RMSE index of the input image of the ISTD+ dataset in your paper measured with your matlab code? I tested different results, and I am confused about the evaluation indicators. I hope you can help me answer my doubts, thank you.
  
Yes, I double-checked, the number is correct.
 
SRD Dataset set the paths of the shadow removal result and the dataset in demo_srd_release.m and then run it.
 Get the following Table 1 in the main paper on the SRD (size: 256x256).
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by jinyeying** [comment]
> 
For AISTD, the number is the same as the paper.
https://www.dropbox.com/sh/foqmi8olum6n3qz/AADX3aQ4yzWvKHh4wtAF6YREa?dl=0

**Comment by Halfpoint1** [comment]
I tried it again. I found that your method is the same as the paper, but got different results for the Input Image of AISTD.







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jinyeying/DC-ShadowNet-Hard-and-Soft-Shadow-Removal"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月6日(星期四) 中午11:00
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jinyeying/DC-ShadowNet-Hard-and-Soft-Shadow-Removal] evaluation (Issue #4)





   
For AISTD, the number is the same as the paper.
 https://www.dropbox.com/sh/foqmi8olum6n3qz/AADX3aQ4yzWvKHh4wtAF6YREa?dl=0
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by jinyeying** [comment]
> I tried it again. I found that your method is the same as the paper, but got different results for the Input Image of AISTD.
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "jinyeying/DC-ShadowNet-Hard-and-Soft-Shadow-Removal" ***@***.***&gt;; 发送时间:&nbsp;2022年1月6日(星期四) 中午11:00 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [jinyeying/DC-ShadowNet-Hard-and-Soft-Shadow-Removal] evaluation (Issue #4) For AISTD, the number is the same as the paper. https://www.dropbox.com/sh/foqmi8olum6n3qz/AADX3aQ4yzWvKHh4wtAF6YREa?dl=0 — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

For the input, we get the number from the paper “from shadow segmentation to shadow removal”. You can find their paper as a reference. Our evaluation code is the same as theirs.

**Comment by Halfpoint1** [comment]
Thank you very much.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jinyeying/DC-ShadowNet-Hard-and-Soft-Shadow-Removal"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月6日(星期四) 下午3:53
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jinyeying/DC-ShadowNet-Hard-and-Soft-Shadow-Removal] evaluation (Issue #4)





  
I tried it again. I found that your method is the same as the paper, but got different results for the Input Image of AISTD.
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "jinyeying/DC-ShadowNet-Hard-and-Soft-Shadow-Removal" @.&gt;; 发送时间:&nbsp;2022年1月6日(星期四) 中午11:00 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [jinyeying/DC-ShadowNet-Hard-and-Soft-Shadow-Removal] evaluation (Issue #4) For AISTD, the number is the same as the paper. https://www.dropbox.com/sh/foqmi8olum6n3qz/AADX3aQ4yzWvKHh4wtAF6YREa?dl=0 — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: @.***&gt;
  
For the input, we get the number from the paper “from shadow segmentation to shadow removal”. You can find their paper as a reference. Our evaluation code is the same as theirs.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by jinyeying** [comment]
> 

Welcome, and I may close the question.
