### ISSUE TITLE
I am confused about the quantitative results in table1(RMSE on SRD). 

### ISSUE THREAD

**Issue by nachifur** [jinyeying/DC-ShadowNet-Hard-and-Soft-Shadow-Removal#5]
Your work is novel. Thank you for your great work! 
I am confused by the quantitative results in Table 1, they seem to be much better than the results in the original paper. How are these results obtained? 
![image](https://user-images.githubusercontent.com/23144348/156185891-d0587f45-da19-4cbe-83b4-a3247a1f6414.png)
I am very much looking forward to your reply. 
Thanks again for your work.

**Comment by jinyeying** [comment]
> Your work is novel. Thank you for your great work! I am confused by the quantitative results in Table 1, they seem to be much better than the results in the original paper. How are these results obtained? ![image](https://user-images.githubusercontent.com/23144348/156185891-d0587f45-da19-4cbe-83b4-a3247a1f6414.png) I am very much looking forward to your reply. Thanks again for your work.

SRD Dataset set the paths of the shadow removal result and the dataset in demo_srd_release.m and then run it.
Get the following Table 1 in the main paper on the SRD (size: 256x256).

**Comment by jinyeying** [comment]
> Your work is novel. Thank you for your great work! I am confused by the quantitative results in Table 1, they seem to be much better than the results in the original paper. How are these results obtained? ![image](https://user-images.githubusercontent.com/23144348/156185891-d0587f45-da19-4cbe-83b4-a3247a1f6414.png) I am very much looking forward to your reply. Thanks again for your work.

In their original papers, the image resolution they use is the original image size.
Since I used RTX 2080 Ti to train the model with 256x256 image resolution, all the baseline results are resized to 256x256 for a fair comparison.
