### ISSUE TITLE
LRSS evaluation

### ISSUE THREAD

**Issue by sagniklp** [jinyeying/DC-ShadowNet-Hard-and-Soft-Shadow-Removal#6]
Could you please clarify which model is used for the LRSS evaluation? Thanks!

**Comment by jinyeying** [comment]
> LRSS

We used the pre-trained SRD model and finetune on the LRSS dataset to get the new model.

**Comment by sagniklp** [comment]
Thank you for the clarification! Is it possible to release that model as well?

**Comment by jinyeying** [comment]
> Thank you for the clarification! Is it possible to release that model as well?

Hi, since test time training is single image-based (for every single image from the LRSS dataset), there is no model for the whole LRSS dataset.
