### ISSUE TITLE
datasets preprocessing code seem not exist

### ISSUE THREAD

**Issue by xzltc** [jinyeying/DC-ShadowNet-Hard-and-Soft-Shadow-Removal#7]
Hi! the paper was cool! thanks for you share! I want to test the model locally, but the code in project only find test model and dataset class, so the code like generate chromaticity maps function had not be release?

> Download Datasets and run 1. get the Shadow-Free Chromaticity Maps after Illumination Compensation, and put them in the trainC folder, you should see the following directory structure.

**Comment by jinyeying** [comment]
> Hi! the paper was cool! thanks for you share! I want to test the model locally, but the code in project only find test model and dataset class, so the code like generate chromaticity maps function had not be release?
> 
> > Download Datasets and run 1. get the Shadow-Free Chromaticity Maps after Illumination Compensation, and put them in the trainC folder, you should see the following directory structure.

You can give me your email and I will send you the code.

**Comment by xzltc** [comment]
xziltc@163.com  It's my email, thanks very much!

**Comment by IAGirl-dev** [comment]
hello, would it be possible to have the generating chromaticity code too ?
my email is : hiba.kehchai@gmail.com

**Comment by Jo3y777** [comment]
hi, would you please send me the code too? It will help me a lot. And my e-mail is 254835509@qq.com. Thanks!

**Comment by xzltc** [comment]
Hi! Sorry to trouble you. have you already sent the email, I haven't received it yet

**Comment by xzltc** [comment]
> > Hi! the paper was cool! thanks for you share! I want to test the model locally, but the code in project only find test model and dataset class, so the code like generate chromaticity maps function had not be release?
> > > Download Datasets and run 1. get the Shadow-Free Chromaticity Maps after Illumination Compensation, and put them in the trainC folder, you should see the following directory structure.
> 
> You can give me your email and I will send you the code.

Hi! Sorry to trouble you. have you already sent the email, I haven't received it yet

**Comment by jinyeying** [comment]
sent already

**Comment by xzltc** [comment]
> 

ops! I Haven't received it yet until now, could you please send to 962059644@qq.com, thanks a lot !!

**Comment by xzltc** [comment]
> sent already
ops! I Haven't received it yet until now, could you please send to 962059644@qq.com, thanks a lot !!

**Comment by xzltc** [comment]
> sent already

ops! I Haven't received it yet until now, could you please send to 962059644@qq.com, thanks a lot !!

**Comment by WangJunjie97** [comment]
Your work is great. Can you send me a copy of the data processing code? My email address is: wbwangjunjie@stu.cqut.edu.cn, thank you very much.

**Comment by jinyeying** [comment]
Hi all,
Thank you for your interest in our works.
Shadow-Free Chromaticity Maps are the implementation of Finlayson's paper,
On the removal of shadows from images (TPAMI,05).

If you want the code, you can contact my email sent by your affiliation email with your signed name.
