### ISSUE TITLE
running the code

### ISSUE THREAD

**Issue by IAGirl-dev** [jinyeying/DC-ShadowNet-Hard-and-Soft-Shadow-Removal#8]
hello,i found your research quit interessting and as am new to programming I coudn't figure out how to run your program properly ,  would it be possible to have more directions or a code implementation exemple on google colab please ?

**Comment by jinyeying** [comment]
> hello,i found your research quit interessting and as am new to programming I coudn't figure out how to run your program properly , would it be possible to have more directions or a code implementation exemple on google colab please ?

hello, you could follow the Test README,
python main_test.py --dataset SRD --datasetpath [path_to_SRD dataset] --use_original_name False,

google colab is a good idea, I will try it when I have time.
